### ISSUE TITLE
DISPLAY exporter fails if ipconfig.exe is not found in $PATH

### ISSUE THREAD

**Issue by jc-roman** [Opticos/GWSL-Source#10]
Error occurs if Windows' $PATH env var is not merged into WSL's $PATH. Fails with "expr: syntax error: unexpected argument '4' ":

```console
ipconfig_exec=$(wslpath "C:\\Windows\\System32\\ipconfig.exe")
> if [ -x $(which ipconfig.exe) ]
> then
>     ipconfig_exec=$(which ipconfig.exe)
> fi
> wsl2_d_tmp=$($ipconfig_exec | grep -n -m 1 "Default Gateway.*: [0-9a-z]" | cut -d : -f 1)
> if [ -n $wsl2_d_tmp ]
> then
rst_lin>     first_line=$(expr $wsl2_d_tmp - 4)
>     wsl2_d_tmp=$($ipconfig_exec | sed $first_line,$wsl2_d_tmp!d | grep IPv4 | cut -d : -f 2 | sed -e "s|\s||g" -e "s|\r||g")
>     export DISPLAY="$wsl2_d_tmp:0"
> else
>     export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk "{print $2}"):0
> fi'
++ wslpath 'C:\Windows\System32\ipconfig.exe'
+ ipconfig_exec=/c/Windows/System32/ipconfig.exe
++ which ipconfig.exe
+ '[' -x ']'
++ which ipconfig.exe
+ ipconfig_exec=
++ grep -n -m 1 'Default Gateway.*: [0-9a-z]'
++ cut -d : -f 1
+ wsl2_d_tmp=
+ '[' -n ']'
++ expr - 4
expr: syntax error: unexpected argument ‘4’
```

**Comment by Pololot64** [comment]
I will gladly push this but I have a question. Don't you think it would be better to simply add "export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk "{print $2}"):0" to the files? That is what I used to have and the simplicity worked much better. The current script for example does not work in some languages.

**Comment by jc-roman** [comment]
> I will gladly push this but I have a question. Don't you think it would be better to simply add "export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk "{print $2}"):0" to the files? That is what I used to have and the simplicity worked much better. The current script for example does not work in some languages.

That was my first thought too. I chose to leave it as is for if the author has some use case I'm not familiar with. I'm using Ubuntu 18 LTS with WSL2 and both methods return the same IP. 

I can replace everything just with the /etc/resolv.comf based method if there's no underlying reason for the current method.

**Comment by Pololot64** [comment]
Sure. I think the simplicity is better.
