### ISSUE TITLE
GWSL is very slow on lower end device

### ISSUE THREAD

**Issue by wolf-yuan-6115** [Opticos/GWSL-Source#100]
**Running OS:** latest windows 11 insider build
**Install from:** Microsoft Store

**Comment by wolf-yuan-6115** [comment]
Sorry, I'm using Windows 11, after i click gwsl icon in taskbar, I need to
wait 30~40 seconds.
idk why

**Comment by Pololot64** [comment]
What kind of specs do you have?

**Comment by wolf-yuan-6115** [comment]
I have a Intel i5 CPU and I have Ubuntu subsystem installed
I have 8GB ram, 512 GB SSD storage

**Comment by Pololot64** [comment]
Those specs look fine. An i5 should be much more than enough (I made gwsl using an i5). Unless it is an extremely old generation of i5 things should be working. What resolution are you running it at?

**Comment by wolf-yuan-6115** [comment]
FHD, 1080P 50Hz

**Comment by Pololot64** [comment]
It might just be a specific problem with your pc. Idk how fast it is with other things but there are so many things that could go wrong on a machine

**Comment by wolf-yuan-6115** [comment]
> It might just be a specific problem with your pc. Idk how fast it is with other things but there are so many things that could go wrong on a machine

hm, ok
Cuz GWSL is slow, so I just installed Ubuntu on my laptop directly...
Thanks for your help <3
