### ISSUE TITLE
Mislabelled scaling options

### ISSUE THREAD

**Issue by zakius** [Opticos/GWSL-Source#104]
When running on 100% the Windows scaling is much sharper than Linux so the labels are misleading. Additionally it probably should default to Windows scaling when detected 100% DPI. When set to 150% though it is as stated, Linux is sharper

**Comment by zakius** [comment]
yes, when systemwide scaling is set to 100% using the default, labelled as "sharper but slower" is blurry and the one marked as "faster but blurier" is sharper

it may depend on the graphics card or the exact panel screen too, but this is my experience on GTX1650 (the first variant) with studio drivers and IPS panel

**Comment by Pololot64** [comment]
That may be it. The linux scaling options literally just tells windows to do nothing. So technically there should be nothing different at 100 percent. I don't want to detect dpi automatically (because manual is better for most people). For reference do you have screenshots?

**Comment by zakius** [comment]
okay, so this is weird as now I can't recreate any difference in rendering at all

may it be that something was misconfigured after fresh install but after changing scaling modes few times and DPI in Windows it got overwritten so it works properly now? I can't provide a screenshot now as everything looks just normal (and images are pixel-perfect the same from both modes) but on the first launch text was almost twice as thick as expected and *fluffy* due to lack of better word

**Comment by zakius** [comment]
as we have no real way of finding the source I guess that's all there's left to do

**Comment by Pololot64** [comment]
Yep. But it probably wont happen again so were good :)
