### ISSUE TITLE
Allow selection of display number

### ISSUE THREAD

**Issue by nicola-lunghi** [Opticos/GWSL-Source#109]
I have sometimes another X server running on  the same machine (mobaxterm)
When mobaxterm is already started, GWSL crashes on startup as the display 0.0 is already taken.
Can the display to use be specified in the configuration??

**Comment by nicola-lunghi** [comment]
or mobaxterm for example tries wirst display 0.0 then if its already taken  -> test the next

**Comment by Pololot64** [comment]
To make all the shortcuts work and everything, I had to stick with 0. There is unfortunately no way for me to change it easily. Can moba xterm's be changed?
