### ISSUE TITLE
Several wsl machines, but I have only one running

### ISSUE THREAD

**Issue by TRB-Exe** [Opticos/GWSL-Source#110]
What to do with it. Restart many times but nothing changes
![IMAGE](https://cdn.discordapp.com/attachments/873863109670993940/904732528684982362/unknown.png)

**Comment by Pololot64** [comment]
You need to update wsl to wsl2

**Comment by TRB-Exe** [comment]
Same. I reinstalled, rebooted, but still nothing has changed
