### ISSUE TITLE
All white game content screen on SpaceCadetPinball

### ISSUE THREAD

**Issue by win98se** [Opticos/GWSL-Source#116]
When I try to run [SpaceCadetPinball](https://github.com/k4zmu2a/SpaceCadetPinball), the game content screen is all white, as shown in below pic.

![image](https://user-images.githubusercontent.com/11819816/143916780-4c9d9cd9-7f34-4e75-b648-740556dfae5d.png)

**Comment by Pololot64** [comment]
It is probably simply incompatible with wsl. Opengl programs often break and there are too many variables to debug this. I unfortunately cannot do anything to fix this.
