### ISSUE TITLE
Firewall Allowing Problem

### ISSUE THREAD

**Issue by rezaf28** [Opticos/GWSL-Source#121]
Hi!
Please Add Firewall button to run this Command on Power Shell.
`New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow`
thanks.

**Comment by Pololot64** [comment]
I'd rather not have GWSL mess with the firewall without a user's knowledge. Thanks for the idea though.
