### ISSUE TITLE
X Server already running

### ISSUE THREAD

**Issue by Jiayi-Pan** [Opticos/GWSL-Source#122]
I'm using WSL2 with WSLg and GWSL. 

Running GUI apps (like Emacs) through GWSL is working fine for me
However, when trying to open a XFCE desktop environment through GWSL shortcut, I got no response at all.

When typing ```startxfce4``` in CLI, I got
```
startxfce4                                                                                    
/usr/bin/startxfce4: X server already running on display 172.28.112.1:0
xrdb: Connection timed out
```

Is it a compatibility issue with WSLg? And do you have any directions on how to solve it?

PS: I don't mind to broke WSLg, as long as GPU CUDA acceleration remains fine.

**Comment by Pololot64** [comment]
I think you may need to go into wslconfig and disable wslg for GWSL to work

**Comment by Jiayi-Pan** [comment]
Sorry, it turns out to be a wrong setting in Shortcut. Solved by giving sudo permission and force single window
