### ISSUE TITLE
Shortcut Creator doesn't work with a bash script

### ISSUE THREAD

**Issue by gazchap** [Opticos/GWSL-Source#123]
First of all, nice work on GWSL - works flawlessly so far, other than this issue!

I've got a single WSL2 distro installed - Ubuntu 20.04 - and I have installed JetBrains PhpStorm on that distro following the instructions on their site.

That software package is started using a bash script in the program directory `phpstorm.sh` which I've aliased to `phpstorm` in my `.bash_aliases`

Shortcut Creator doesn't seem to work here though, if I tell it to run either `phpstorm` or the full path to the script (i.e. what it's aliased to) nothing happens.

Am I missing something super simple? It's been a long time since I did anything with Linux...

**Comment by gazchap** [comment]
Typical, tried something slightly different just after posting this and it works - previously I was using `> /dev/null 2>&1 &` on the command (as that was in the alias) - removing that makes it work fine.

It still doesn't seem to work with aliases though, is that normal?

**Comment by gazchap** [comment]
No, dashboard.log is completely empty.

**Comment by Pololot64** [comment]
Do you have any idea if WSL updated recently on your pc?

**Comment by gazchap** [comment]
Not a clue I'm afraid, how would I find out? It's a relatively recent install if that helps - couple of weeks old.

**Comment by gazchap** [comment]
It works fine with xclock, yup.

**Comment by Pololot64** [comment]
Ok. Well, that eliminates one problem. Can you take a screenshot of the shortcut manager with the settings you are using? Before clicking save.

**Comment by gazchap** [comment]
Sure - I've opened up the more options panel for clarity, but it doesn't matter whether that's open or not.

![image](https://user-images.githubusercontent.com/9681509/150359832-d75066da-ed52-4ee5-a3e3-c8b923699f94.png)

**Comment by Pololot64** [comment]
If you use a direct path to the sh file, what happens if you start it with ./  ?

**Comment by gazchap** [comment]
Yeah, if I use the full path to the .sh file that the alias is pointing to, it works fine.

Does not work if I put ./ before the alias.

**Comment by Pololot64** [comment]
In that case it may just be best to not use the alias I guess. The method I use of calling the program must have some conflict with it.

**Comment by gazchap** [comment]
Fair enough :)
