### ISSUE TITLE
wt not opening in 'Graphical SSH connection'

### ISSUE THREAD

**Issue by plutonium-239** [Opticos/GWSL-Source#126]
I have set 'shell_gui' to 'wt' correctly in the json, and linux shell opens in wt automatically.
However, graphical SSH connection opens in a PuTTY window and looks very bad. I know you can customize that window but I would like it if ssh also opens in wt.
I can't seem to find any other issue/documentation on it

**Comment by Pololot64** [comment]
You will have to do that manually. GWSL uses putty for ssh and there is no way to change it.
