### ISSUE TITLE
Don't use '-primary' for clipboard options by default and/or make it configurable

### ISSUE THREAD

**Issue by mavo** [Opticos/GWSL-Source#127]
I am facing the problem, that having `-primary` option enabled makes it impossible to C&P from the windows host to a wsl app when pasting to a selected text.
The problematic part is [here](https://github.com/Opticos/GWSL-Source/blob/7096f959ed14a39f1fce16f1247dd51cf96b47db/manager.py#L2752)

**Reproduction steps:**
1. Start (e. g.) intelliJ via in GWSL
2. Copy some text from windows host
3. Select text/code on intelliJ (DON'T CTRL+C)
4. Try to paste what was copied from windows host

*Observed:*
- Will paste the selected text in intelliJ

*Expected:*
- Should paste/replace selected text with windows copied text

**Why**:
As I was using VcXsrv I faced the same problem, but VcXsrv allows me to disable the option `-primary` which solves the issue I faced. I really do like GWSL, especially since M$ dropped the option to support of WSLg for win10, but this a showstopper for me. I like the shortcut creation option and the really smoooooth integration.
Would be great if this option can be somehow integrated in the GWSL options set.

EDIT: I know I can compile all this on my own, but this is cumbersome.

**Comment by Pololot64** [comment]
Hello Mavo,

You can do this with custom xserver profiles:

From the GWSL discord:
![image](https://user-images.githubusercontent.com/31389383/152659831-36c93b51-c3e3-44e3-a8e5-834d56bb10d8.png)

Right click the GWSL icon in the systray -->Xserver Profiles --> Add A Profile.

Name the profile and add the arguments ```-wgl -compositewm -multiwindow -clipboard -noprimary```

Save it, right click the systray menu again, and switch to it. It should disable primary.

Feel free to bring up any other issues.

Paul

**Comment by mavo** [comment]
Ahhhh `-noprimary` is the key. I was not aware of this. Only thought the "positive" option is possible 💡 
Thanks a lot, will close this one.

**Comment by Pololot64** [comment]
Glad to help :)
