### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Luca-Prezzo** [Opticos/GWSL-Source#13]
I have installed gwsl from the Microsoft store but when i try to start it say "failed to execute script manager"

**Comment by Pololot64** [comment]
I think this is probably one of the issues that has already been documented and fixed for the upcoming release. We can make sure though, can you check the logs and see what they say? https://opticos.github.io/gwsl/tutorials/manual.html#finding-logs

**Comment by Luca-Prezzo** [comment]
I have fixed the issue adding a DWORD entry called SystemUsesLightTheme in the registry editor under "Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize"

**Comment by Pololot64** [comment]
Soon you wont have to do that any more. I am glad this fix works but do not recommend it to anyone just in case there are unintended consequences. I have not tested it but soon it will become unnecessary with the next release of GWSL. Again, this is only if you have this specific bug.

**Comment by jiornojiovanni** [comment]
With the latest release (1.3.7) it also happen to me. I checked the registry and the key mentioned by @Luca-Prezzo is there, so it's probably something else now.

**Comment by Pololot64** [comment]
Oh shoot... Maybe I'd better pull it back. What is the log error now?

**Comment by jiornojiovanni** [comment]
"failed to execute script manager", maybe it's my machine

**Comment by Pololot64** [comment]
Is the line number the same? I think I have a fix but I need to rebuild

**Comment by jiornojiovanni** [comment]
> Is the line number the same? I think I have a fix but I need to rebuild

Where I can check the log? I only get the message box with that text

**Comment by Pololot64** [comment]
https://opticos.github.io/gwsl/tutorials/manual.html#finding-logs :-)

**Comment by Pololot64** [comment]
Any luck?

**Comment by jiornojiovanni** [comment]
dashboard.log
```
2020-12-21 09:17:21,374 - GWSL 1.3.7 - ERROR - Exception occurred
Traceback (most recent call last):
  File "manager.py", line 317, in <module>
KeyError: 'start_menu_mode'
2020-12-21 09:18:36,750 - GWSL 1.3.7 - ERROR - Exception occurred
Traceback (most recent call last):
  File "manager.py", line 317, in <module>
KeyError: 'start_menu_mode'
2020-12-21 14:24:35,886 - GWSL 1.3.7 - ERROR - Exception occurred
Traceback (most recent call last):
  File "manager.py", line 317, in <module>
KeyError: 'start_menu_mode'
```
service.log is empty.

**Comment by Pololot64** [comment]
Phew! Ok. That error is not too bad. Where the logs are, delete settings.json

**Comment by Pololot64** [comment]
Then it will run

**Comment by Pololot64** [comment]
Did you have the alpha version before?

**Comment by jiornojiovanni** [comment]
I had 1.3.6 from the windows store, uninstalled it and then installed 1.3.7 from github.

**Comment by Pololot64** [comment]
So store 1.3.6 and the the new github 1.3.7?

**Comment by jiornojiovanni** [comment]
> So store 1.3.6 and the the new github non-alpha 1.3.7?

Only the github version is installes right now.

**Comment by Pololot64** [comment]
I released the 1.3.7 stable version. If you still want to try, I recommend uninstalling the old alpha GWSL first and deleting the GWSL folder in user/appdata/roaming.

**Comment by jiornojiovanni** [comment]
Tried it with VLC, it works!
GIMP starts but when after entering the editor it crashes.

**Comment by Pololot64** [comment]
I had the same problem with gimp. I think it is just some strange WSL incompatibility. I never looked into it because I already have GIMP on Windows.

**Comment by Pololot64** [comment]
Closing the issue :) Thanks for the help!
