### ISSUE TITLE
start with windows

### ISSUE THREAD

**Issue by dolorain** [Opticos/GWSL-Source#134]
once i installed gwsl, i cant open wsl applications without gwsl.
so i must run gwsl first.
but i always forgot it.
plz add this option in gwsl.

**Comment by dolorain** [comment]
or let me know how to run wsl application without gwsl.
for now, it seems like x-window-server had some problems make it cant auto run with the wsl command.

**Comment by Pololot64** [comment]
Um. Did you find an answer? There is one in the manual.
