### ISSUE TITLE
Cannot launch nor add functionning shortcut to a linux app that I have built myself (under Microsoft Store's Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by MisesEnForce** [Opticos/GWSL-Source#140]
I installed Ubuntu 20.04 from Microsoft Store for WSL2.
In it I made all updates/upgrades and made sure I had C/C++ compilers from GCC. Then I did this : 

`sudo apt-get install make libexpat1-dev libfontconfig1-dev libfreetype6-dev libxft-dev libxcursor-dev tcl8.6 tcl8.6-dev tk8.6 tk8.6-dev zlib1g-dev`

`svn checkout https://svn.code.sf.net/p/scidb/code/trunk scidb-code`

`cd trunk scidb-code`

`./configure`

`make`

`sudo make install`

which installed the binaries in /usr/local/bin : 

![image](https://user-images.githubusercontent.com/5349602/160122367-771a6322-e419-4baf-9c42-03147b25a9b4.png)

Would I be in a standard (graphical) Ubuntu I would laucnh the app by executing the scidb-beta command in /usr/local/bin and the app would work like a charm. In WSL2+Ubuntu 20.04 LTS+GWSL it is another story.

I tried to create a shortcut in GWSL to /usr/local/bin/scidb-beta and to use it : nothing was lauched. As in a standard Ubuntu this app would not appear in "ubuntu app", the app does not appear in GSWL "linux apps", so in Ubutun 20.04 LTS in WSL2, I wen to /usr/share/applications, created a scidb.desktop file containing : 

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=/usr/local/bin/scidb-beta
Name=Scidb
Comment=Chess database handling
Icon=/usr/local/bin/icon.png

sudo save it, then did a sudo chmod +x ./scidb.desktop on it.

I went back in GWSL "linux app", and this time (logical !) the scidb app appeared, but launching it did not launch anything.
I if may help, the app relies on TCL and TK, and would I launch it in the Ubuntu 20.04 LTS WSL2 terminal, I would get a : 

application-specific initialization failed: no display name and no $DISPLAY environment variable
Error in startup script: no display name and no $DISPLAY environment variable
    while executing
"load /usr/lib/x86_64-linux-gnu/libtk8.6.so Tk"
    ("package ifneeded Tk 8.6.10" script)
    invoked from within
"package require Tk  8.5"
    (file "/usr/local/bin/scidb-beta" line 34)

Naturally, in a vanilla "graphical" Ubuntu, all of this would have worked liek a charm. As it actually does on an Ubuntu machine I have. Do I miss something in GWSL ?

**Comment by MisesEnForce** [comment]
![image](https://user-images.githubusercontent.com/5349602/160247574-f468a631-3237-49a8-90ac-8df143631b10.png)
I indeed clicked the display audio/video exporting.
I don't use a custom shel (I use the one coming with the Ubuntu Install from Microsoft Store.)
I am under Windows 11 last update.

**Comment by Pololot64** [comment]
It is possible that Microsoft's wslg installed itself and is conflicting. It is possible to turn off by creating a file in your Windows user folder called ```.wslconfig``` with the contents ```[wsl2]
guiApplications=false```

**Comment by MisesEnForce** [comment]
Just did it. Same result.

**Comment by Pololot64** [comment]
Did you restart the machine?

**Comment by MisesEnForce** [comment]
I did, yes.

**Comment by MisesEnForce** [comment]
Actually I just `sudo apt install libreoffice`, the apps appears in linux apps in GWSL, but I have the same issue with them as I have we my built app : when I click on one of them, nothing happens.

**Comment by Pololot64** [comment]
So it complains DISPLAY is not set?

**Comment by MisesEnForce** [comment]
![image](https://user-images.githubusercontent.com/5349602/160254121-10bfe788-87aa-4ced-a929-2bde061c47ad.png)

**Comment by Pololot64** [comment]
Ok. Try deleting all the firewall rules with GWSL and vcxsrv and restart gwsl

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
