### ISSUE TITLE
GWSL on company PC not working

### ISSUE THREAD

**Issue by CodoMg** [Opticos/GWSL-Source#144]
Hy, 

I run GWSL on my Personal PC without problems, but on my company laptop, GWSL cannot set Autoexport Display/Audio.
Ubuntu 20.04 over WSL2

I checked the Windows Event Viewer for logs and found this:

Translated from German:

> Permission settings for "Computer Default" do not grant permission of type to user "xxxxxx" (SID: S-1-5-21-1390067357-484061587-839522115-4645) at address "LocalHost (using LRPC)". "Activate locally" for the COM server application with the CLSID
> {C2F03A33-21F5-47FA-B4BB-156362A2F239}
>   and the APPID
> {316CDED5-E4AE-4B15-9113-7055D84DCC97}
>   granted in the application container "Microsoft.Windows.ShellExperienceHost_10.0.19041.1320_neutral_neutral_cw5n1h2txyewy" (SID: S-1-15-2-155514346-2573954481-755741238-1654018636-1233331829-3075935687-28068147-28068147-28068147 The security permission can be changed using the Component Services administration tool.
>

I allowed every GWSL entry in the Firewall.

![image](https://user-images.githubusercontent.com/56188324/161932710-5298dfa6-8b95-4696-89d8-d1886244abc5.png)

Thanks

**Comment by Pololot64** [comment]
Can you try with the github version of GWSL?
