### ISSUE TITLE
GWSL escaping underscore in DistributionName

### ISSUE THREAD

**Issue by felipe257** [Opticos/GWSL-Source#145]
I have installed Rocky 8 RC Unofficial through Microsoft Store and it names the distro in wsl as "Rocky_8_RC_Unofficial".

![image](https://user-images.githubusercontent.com/2503639/162587430-b77dc7a6-ade6-4cd2-abfc-a27daf3b3c3a.png)

I then installed GWSL and it would consider "Rock8RCUnofficial" as the DistributionName instead, which results in GWSL not working at all. A workaround I've found is to change the DistributionName manually in the Registry Editor from "Rocky_8_RC_Unofficial" to "Rock8RCUnofficial".

![image](https://user-images.githubusercontent.com/2503639/162587533-a2486a29-9e67-4c81-88a2-a0b81367731d.png)

I understand GWSL should not be escaping "_" for DistributionName, thus I'm reporting it as an issue.

**Comment by Pololot64** [comment]
Fixed 1.4.5
