### ISSUE TITLE
Limiting window size

### ISSUE THREAD

**Issue by g0r3** [Opticos/GWSL-Source#147]
Hi,

1. I would like to use GWSL in the multiwindow mode, but at the same time set an upper limit of the window size of the window for maximizing. The problem is that I use a HiDPI screen and the chrome browser in the WSL shows everything with no scaling at all.

2. Also the full sceen seems to be a bit fishy right now. I only can see some flickering and I have to click on the application icon in the taskbar minimizing and maximizing the application in order to see it.

Is there away to achieve 1/avoid 2?

**Comment by g0r3** [comment]
Ok, I think I at least got the reason for problem 2:

If I look in WSL, a wrong screen resolution gets reported:
``` 
>$ xrandr                                                                       
Screen 0: minimum 0 x 0, current 5760 x 2560, maximum 32767 x 32767
default connected primary 5760x2560+0+0 1016mm x 451mm
   5760x2560      0.00*
```
My screen has 3840x2560. Is there a way to correct this? Creating a new mode with xrandr didn't work.

**Comment by Pololot64** [comment]
Can you try googling this for vcxsrv?
