### ISSUE TITLE
prerequisite in WSL?

### ISSUE THREAD

**Issue by HuStmpHrrr** [Opticos/GWSL-Source#150]
I might be dumb but I could find what I need to install in WSL (Ubuntu specially) for gwsl to work. I did install gnome already but otherwise nothing seems to work (e.g. not finding any app). Any reference on what to do in a fresh WSL distro?

**Comment by Pololot64** [comment]
You can pretty much install any graphical app you want. Gnome is not needed. For example, you could install the synaptic package manager and run that as root to get more apps or install things like firefox manually.

**Comment by HuStmpHrrr** [comment]
@Pololot64 are you saying there is no configuration is required? I do have ubuntu 20.04 with gnome installed but gwsl cannot discover any app.

**Comment by Pololot64** [comment]
What apps have you tried? Also have you changed the default shell from bash?

**Comment by HuStmpHrrr** [comment]
I installed a fresh Ubuntu and it seems to work seamlessly! I am not sure what's messing up cuz my old way was to use systemd to launch a full gnome desktop. If I run from a shortcut, it seems to just work. The only problem is that it is not possible to scan the apps but I can live with that!

**Comment by Pololot64** [comment]
Ok. Yeah. Sometime the app scanning doesn't work properly (since it is quite complex) but I am glad shortcuts work.
