### ISSUE TITLE
How i can change window color to dark? 

### ISSUE THREAD

**Issue by Grzyb9k** [Opticos/GWSL-Source#152]
In my WIndows 11 i use dark theme, but my phpstorm(and any other app) opened with GWSL have white window title bar. 
How i can change that? 

![image](https://user-images.githubusercontent.com/73300122/169471068-f27f92e7-bde1-4cd9-a34c-9862a67ee576.png)

**Comment by Pololot64** [comment]
Unfortunately, you cannot change this as it is the default Windows titlebar. You can always use an app like Mica For Everyone to force dark titlebars around the OS but I haven't tested it.

**Comment by Pololot64** [comment]
I tested Mica For Everyone with a GWSL game: 
![image](https://user-images.githubusercontent.com/31389383/169555138-58fc149b-eb38-46cc-869f-94aaf9f1708f.png)

It seems to work. You can add a rule in the app for the process GWSL_vcxsrv and set the default titlebar mode to dark:
![image](https://user-images.githubusercontent.com/31389383/169555658-8cdf84c1-20bf-420a-8948-c0a55787cb17.png)

**Comment by ChGen** [comment]
Actually, there are Win32 APIs to support dark mode in Win32 based applications, like `DwmSetWindowAttribute()` 
So, title bars could be made dark:
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes

**Comment by Pololot64** [comment]
The thing is, this code would have to be implemented into the vcxsrv source code which I would rather not do.
