### ISSUE TITLE
How to creat a profile without title bar

### ISSUE THREAD

**Issue by ngvq** [Opticos/GWSL-Source#159]
I want to creat a custom profile without title bar as VcXSrv. But i can't do it. I don't want to use Fullcreen profile because it very slow on my machine when i switch between Windows apps and GWSL. I'm finding a solution for this

**Comment by ngvq** [comment]
> Hi,
> 
> Yes this can be done. Simply right click the GWSL systray icon --> Xserver Profiles --> Add a Profile.
> 
> Give the profile a name like "Single Window Borderless" and enter the flags `-wgl -compositewm -clipboard -nodecoration`
> 
> Save the profile and switch to it using the Xserver Profiles menu again. ![image](https://user-images.githubusercontent.com/31389383/182444914-9ee5dc1e-0109-4b1c-b6e5-6e58da2debe9.png)
It worked. Thanks a lot for support me. I can use WSL likely VcXSrv without title bar

**Comment by ngvq** [comment]
> Hi,
> 
> Yes this can be done. Simply right click the GWSL systray icon --> Xserver Profiles --> Add a Profile.
> 
> Give the profile a name like "Single Window Borderless" and enter the flags `-wgl -compositewm -clipboard -nodecoration`
> 
> Save the profile and switch to it using the Xserver Profiles menu again. ![image](https://user-images.githubusercontent.com/31389383/182444914-9ee5dc1e-0109-4b1c-b6e5-6e58da2debe9.png)

It worked. Thanks a lot for support me. I can use WSL as VcXSrv without titlebar

**Comment by Pololot64** [comment]
I'm happy to help :)
