### ISSUE TITLE
Disable PRIMARY when using clipboard

### ISSUE THREAD

**Issue by M0nik** [Opticos/GWSL-Source#16]
Hello!
Could you add the ability to disable PRIMARY when using clipboard?
In VcXsrv this is implemented, but in GWSL it is hardcoded:
```
if clipboard == True:
  default_arguments.append("-clipboard")
  default_arguments.append("-primary")
else:
  default_arguments.append("-noclipboard")
  default_arguments.append("-noprimary")
```

**Comment by Pololot64** [comment]
It is not actually hardcoded in the code any more. What I will have in the next release is a system of "xserver profiles" that have their own switches they pass. You can use the new gui to make a new profile with any switches. Then you can switch between these profiles in the systray menu

**Comment by M0nik** [comment]
It is perfectly. Thanks!

**Comment by JYInMyHeart** [comment]
> It is perfectly. Thanks!

HI. Could you please tell me where we should add these arguements when disable PRIMARY.

**Comment by Pololot64** [comment]
> > It is perfectly. Thanks!
> 
> HI. Could you please tell me where we should add these arguements when disable PRIMARY.

To do this, right click the gwsl systray icon --> XServer Profiles --> Add A Profile. Create a profile with the arguments ```-wgl -compositewm -multiwindow -clipboard -noprimary```

**Comment by JYInMyHeart** [comment]
Thank you so much!

> > > It is perfectly. Thanks!
> > 
> > 
> > HI. Could you please tell me where we should add these arguements when disable PRIMARY.
> 
> To do this, right click the gwsl systray icon --> XServer Profiles --> Add A Profile. Create a profile with the arguments `-wgl -compositewm -multiwindow -clipboard -noprimary`

Thank you so much!
