### ISSUE TITLE
Issue trying to open GWSL 1.4.0

### ISSUE THREAD

**Issue by TwelfthDoctor1** [Opticos/GWSL-Source#161]
When I am trying to open GWSL (store version), nothing happens. So I decided to check `dashboard.log` and this error is listed there:
```
2022-08-27 16:10:57,444 - GWSL 1.4.0 - ERROR - Exception occurred - Config generation
Traceback (most recent call last):
  File "manager.py", line 224, in <module>
  File "subprocess.py", line 630, in getoutput
  File "subprocess.py", line 611, in getstatusoutput
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 488, in run
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Im not sure if it is able to find settings.json (I guess not) even though it was able to create it based on this error.

**Comment by TwelfthDoctor1** [comment]
Also this error does not allow GWSL to continue running.

**Comment by Pololot64** [comment]
Can you screenshot the contents of appdata/roaming/GWSL

**Comment by TwelfthDoctor1** [comment]
<img width="552" alt="Screenshot_87" src="https://user-images.githubusercontent.com/24480582/187058645-2b96a6e6-8a83-49c5-a6d1-326f623dd2aa.png">

**Comment by Pololot64** [comment]
What drive is appdata in?

**Comment by TwelfthDoctor1** [comment]
Its on the C: drive.

**Comment by Pololot64** [comment]
That is strange... Hmm try deleting the GWSL folder and reopening GWSL

**Comment by TwelfthDoctor1** [comment]
Welp that did not work. This is the error that I get.
<img width="201" alt="Screenshot_88" src="https://user-images.githubusercontent.com/24480582/187269522-35dc172f-1c0e-44e2-b71f-9b80126f30d8.png">

**Comment by Pololot64** [comment]
Hmm.. I can only think of reinstalling GWSL completely.. It may be the antivirus

**Comment by TwelfthDoctor1** [comment]
Welp even with a reinstall, it sadly still fails. As what you said, it could most likely be an antivirus issue but since the device is enrolled into a work/school, I do not have control over the antivirus settings for Windows Defender.

**Comment by Pololot64** [comment]
Sorry :/. Something is simply blocking GWSL from working and I can't really bypass that

**Comment by TwelfthDoctor1** [comment]
Yeah. I guess for now I'll have to use GWSL on another device that I've tested it to be working.

**Comment by Pololot64** [comment]
👍 Will close for now
