### ISSUE TITLE
Labels .lnk (by Shortcut Creator)  are limited to 260 charecters

### ISSUE THREAD

**Issue by Copoka11** [Opticos/GWSL-Source#162]
Labels (.lnk) are limited to 260 characters (in my case - Windows 11), and this can probably cause problems when launching the Shortcut
For example:
`C:\Users\<User>\AppData\Roaming\GWSL\GWSL.exe --r --wsl_machine="Ubuntu" --wsl_cmd="startxfce4" --w_mode="Single Window" --clip_enabled="Default" --gtk_scale="Default" --qt_scale="Default" --append="" --theme="follow" --root="false" --dbus="false" --keep="fals`

**Comment by Pololot64** [comment]
This is not actually limited. The entry box in properties in explorer is limited but in reality, the content can be longer.
