### ISSUE TITLE
Cannot fullscreen apps like QEMU in GWSL

### ISSUE THREAD

**Issue by prateekmedia** [Opticos/GWSL-Source#165]
Same as above, Wslg can do that easily, clicking fullscreen just hides titlebar and no fullscreen.

**Comment by Pololot64** [comment]
Is there a terminal flag to launch qemu in fullscreen? Consider setting GWSL to fullscreen mode as well

**Comment by prateekmedia** [comment]
It is there in menu bar, wslg behaves well and fullscreen the window

**Comment by Pololot64** [comment]
?

**Comment by prateekmedia** [comment]
If I set full screen flag then It works but not correctly as the vm is shifted below, I don't know why.

Also I cannot unfullscreen it then, is it possible to add this functionality to gwsl itself?

**Comment by Pololot64** [comment]
There is a fullscreen option in GWSL. Try this: 
![image](https://user-images.githubusercontent.com/31389383/202537983-d2948812-1596-48ce-90f0-8a2807990b06.png)

**Comment by prateekmedia** [comment]
Nice, One Downside is that it takes full screen even if no app is open, otherwise this seems good.
