### ISSUE TITLE
Need exclusive keyboard mode option and a hotkey to exit that mode

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [Opticos/GWSL-Source#166]
The following is the implementation of similar functions in other software： 

Force Virtual Machines to Grab Keyboard and Mouse Input in Vmware

Capture windows logo key in X410

Right-ctrl in VirtualBox

**Comment by Pololot64** [comment]
I am not sure I can do anything about this as I do not change the vcxsrv code. Intercepting keys is not something I want to mess with. Is the problem that a window is capturing your keyboard and/or mouse and not letting go?

**Comment by I-Want-ToBelieve** [comment]
When I press the alt + tab key combination on the linux desktop, I actually switch the focus window of the windows system desktop, which is expected to switch the window of the linux desktop
