### ISSUE TITLE
gwsl with screen readers

### ISSUE THREAD

**Issue by MesterPerfect** [Opticos/GWSL-Source#167]
I can't use gwsl with screen readers, any suggested solutions?

**Comment by Pololot64** [comment]
I do not have a solution for GWSL, the UI is canvas based with all custom widgets

**Comment by MesterPerfect** [comment]
> I do not have a solution for GWSL, the UI is canvas based with all custom widgets

no problem thank you

**Comment by Pololot64** [comment]
You're welcome
