### ISSUE TITLE
Running on 1809 ?

### ISSUE THREAD

**Issue by GoldenHashtag** [Opticos/GWSL-Source#17]
The latest version of Windows 10 LTS* is 1809, which I'm using on my PC. Is it possible to target this project for 1809? Or is there something required by this software not exist in 1809?
![image](https://user-images.githubusercontent.com/40300931/101315190-ff337180-3851-11eb-9af2-4dcf9b92269c.png)
![image](https://user-images.githubusercontent.com/40300931/101315234-11151480-3852-11eb-97dd-900b3f4c57dd.png)

**Comment by Pololot64** [comment]
It cannot run on any versions below 1903 as the older versions do not support WSL 2. GWSL does not have to use the wsl2 backend and can use wsl 1 but when wsl2 came, the command switches controlling wsl changed too and I only support the new ones

**Comment by Pololot64** [comment]
And question because I have never been able to do it, how did you scrape the installer package from the store?

**Comment by GoldenHashtag** [comment]
Download store apps directly (some are encrypted so you get packages with a* prefix file extension and it's impossible to install locally):

- https://store.rg-adguard.net/

Some applications allow on-premise deployment, which you can purchase / download from (enterprise / school account required):

- https://businessstore.microsoft.com/en-us/store/

I've heard one capturing Microsoft Store traffic to get installer package download address using Fiddler but I've never replicated that for once.

- https://www.telerik.com/fiddler
- http://woshub.com/how-to-download-appx-installation-file-for-any-windows-store-app/

Microsoft Store will still automatically update those installed externally.
You still have to purchase apps that are paid, otherwise you won't be able to open it; In-app purchase options are still available. 

BTW I also suggest that you release misx installer on GitHub Releases, many including I prefer this way of installation.
([ModernFlyouts](https://github.com/ShankarBUS/ModernFlyouts), [Windows Terminal](https://github.com/microsoft/terminal))
