### ISSUE TITLE
Network disconnect closes X11 windows

### ISSUE THREAD

**Issue by kportertx** [Opticos/GWSL-Source#18]
The `GWSL_EXPORT_DISPLAY` script uses the IP address attached to my WiFi interface. Replacing this IP address with the IP of the virtual interface labeled "WSL" resolves this issue.

**Comment by kportertx** [comment]
These are the modifications I've made to the `GWSL_EXPORT_DISPLAY` script - note this also include modifications for ZSH and my not run in Bash.

```
#GWSL_EXPORT_DISPLAY
ipconfig_exec=$(wslpath "C:\\Windows\\System32\\ipconfig.exe")
if (( $+commands[ipconfig.exe] ))
then
    ipconfig_exec=$(which ipconfig.exe)
fi

first_line=$($ipconfig_exec | grep -n -m 1 "WSL" | cut -d : -f 1)
if [ -n $first_line ]
then
    last_line=$(expr $first_line + 6)
    end_line=$(expr $last_line + 1)
    wsl2_d_tmp=$($ipconfig_exec | sed -n "${first_line},${last_line}p;${end_line}q" | grep IPv4 | cut -d : -f 2 | sed -e "s|\s||g" -e "s|\r||g")
    export DISPLAY="$wsl2_d_tmp:0"
else
    export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk "{print $2}"):0
fi
```

**Comment by Pololot64** [comment]
I am actually getting rid of this script entirely. I am going to use what Microsoft recommends without any extra fluff. The current solution was supposed to be an update to it but does not work with other languages and does not work with every configuration.

**Comment by Pololot64** [comment]
GWSL 1.3.7 does not have this problem. If you get rid of the old export script, clicking the export button will now add ```export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk "{print $2}"):0```
