### ISSUE TITLE
Can't open a single app

### ISSUE THREAD

**Issue by Rafarel** [Opticos/GWSL-Source#19]
Hello! I don't know to contact you so I do it here 😅

Thanks for sharing your work it is very cool. The problem is I can't see a single application launching on my Windows desktop.
I'm using Ubuntu 20.04 in WSL2 mode.
I just want to open gitkraken for example by launching the gitkraken command. How do I do this ?
Just tried to use a shortcut and test the config.
I know that gitkraken is running on the Ubuntu but nothing happens on the windows side.
Can you help me with that ?
Thanks a lot

**Comment by Pololot64** [comment]
Is the display set to auto export? In wsl what is the value of the Display variable? Sorry. there are many things that can go wrong and I need to start somewhere

**Comment by Rafarel** [comment]
Hi, thanks for your answer! Don't worry I understand ;)
Yes it is set to auto export, the .bashrc has been edited in the linux distro and the $DISPLAY variable is up to date

**Comment by Pololot64** [comment]
Are you able to ping the host's ip from within wsl?

**Comment by Rafarel** [comment]
I'm able to display linux application using X410 that is a paid software to do the same thing but I like your approach with the menu that list the apps. So yes I think that if X410 can show me my apps all is OK. I don not test both X solution at the same time just to be sure when I test yours, X410 is off

**Comment by Pololot64** [comment]
I am pretty sure that X410 uses the same VCXSRV source as GWSL. Technically if it works with one, it should with the other. The next issues to test would be whether the GWSL service is really running and whether it is being blocked by the Windows firewall.

**Comment by Pololot64** [comment]
Also, can the program be launched graphically through bash directly?

**Comment by Pololot64** [comment]
I know this is old but can you verify that GWSL_vcxsrv.exe has public access through the friewall?

**Comment by michalsieron** [comment]
> I know this is old but can you verify that GWSL_vcxsrv.exe has public access through the firewall?

I am not sure if it was the same thing, but that worked for me. The only app I was able to run before, was XClock from about page. When I was running straight from terminal, it would just hang and after some time give up and timeout.

Windows 10 20H2, build 19042, Ubuntu 20.10, WSL2

**Comment by Pololot64** [comment]
Xclock from the about page is an x app that runs on Windows so if it works it is just WSL being blocked. I am glad the solution worked!
