### ISSUE TITLE
Exception after setting display

### ISSUE THREAD

**Issue by vasilvestre** [Opticos/GWSL-Source#2]
After setting auto display parameter through tool and rebooting WSL, here's my error :

```
expr: syntax error: unexpected argument ‘4’
sed: -e expression #1, char 1: unknown command: `,'
expr: syntax error: unexpected argument ‘4’
sed: -e expression #1, char 1: unknown command: `,'
expr: syntax error: unexpected argument ‘4’
sed: -e expression #1, char 1: unknown command: `,'
expr: syntax error: unexpected argument ‘4’
sed: -e expression #1, char 1: unknown command: `,'
```

I used this in bashrc `export DISPLAY="`grep nameserver /etc/resolv.conf | sed 's/nameserver //'`:0"` and it's working

**Comment by Pololot64** [comment]
I am aware of this issue. I used to use the old script but decided to upgrade which was a bad idea. I am simplifying this in the next update. The current script breaks when the Windows firewall is not configured properly.
