### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pywin32

### ISSUE THREAD

**Issue by mslinn** [Opticos/GWSL-Source#20]
```script
$ python --version
Python 3.8.6

$ sudo -H pip3 install 'pywin32==300'
ERROR: Could not find a version that satisfies the requirement pywin32
ERROR: No matching distribution found for pywin32
```

The [pywin32 package exists](https://pypi.org/simple/pywin32/) for all Python3 versions released to date.
I had upgraded the [pip dependency resolver](https://pip.pypa.io/en/latest/user_guide/?s=09#changes-to-the-pip-dependency-resolver-in-20-3-2020), so I tried:

```script
$ sudo -H pip3 install --use-deprecated=legacy-resolver pywin32
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```
Still no luck :(

Then I found this `pywin32` issue: ["WSL does not support pywin32"](https://github.com/mhammond/pywin32/issues/1609). Seems the GWSL-Course installation instructions are for installing on Windows, not WSL. Gee, it would have been really nice to know this up front.

Only after fussing for an hour did I find that I could simply [download the prebuilt package using Microsoft Store](https://www.microsoft.com/p/gwsl/9nl6kd1h33v3?rtc=1&activetab=pivot:overviewtab). Perhaps this information should be put in the project README.

**Comment by Pololot64** [comment]
Strange. They are the build instructions for windows (WSL is not used for building) but I must have made a typo in the requirements. And I'll make it more obvious it can be installed on the store.
