### ISSUE TITLE
$DISPLAY auto-export only works for Windows in English language

### ISSUE THREAD

**Issue by ElSaico** [Opticos/GWSL-Source#23]
The current implementation attempts first to grep the output of `ipconfig.exe` for a line starting with `Default Gateway:`, which is very flaky as it breaks on any other language.

**Comment by Pololot64** [comment]
This has already been changed and will soon not use ipconfig anymore. Thanks for the report though :) Help is always still appreciated!

**Comment by shelper** [comment]
originally i use the following to export my $DISPLAY:
`export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0` and it works as it sets DISPLAY to something like: 
`172.17.0.1:0.0`
but when using gwsl autoexport it does not work, basically it sets my $DISPLAY to something like `192.168.1.2:0` which cannot be opened through my wsl bash

I checked the output of ipconfig and found the following, based on which i wonder why the auto export sets DISPLAY to `192.168.1.2` ? shouldnt' it use the WSL vEthernet to access the IP?

```
Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : ****
   IPv4 Address. . . . . . . . . . . : 172.17.0.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::d5a9:d870:5ecf:cbd6%17
   IPv4 Address. . . . . . . . . . . : 192.168.1.2
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1

```

**Comment by Pololot64** [comment]
I already posted that it has been fixed for the future release. See the post above yours.
