### ISSUE TITLE
Colemak

### ISSUE THREAD

**Issue by octavz** [Opticos/GWSL-Source#24]
Hi , 

How I configure support for Colemak layout?

Thank You.

**Comment by Pololot64** [comment]
As soon as I release this update it will be possible

**Comment by octavz** [comment]
Hi, when you say *this release* what do you mean? can you give me a version number so I know when to download it again. Thank you.

**Comment by Pololot64** [comment]
I mean 1.3.7. I have been working on it for a long time and it needs testing. Unfortunately, I am a human with other important responsibilities so I am doing my best but there are no ETA's. I can message you here when it is ready.

**Comment by octavz** [comment]
No problem, it just wasn't clear for me what version i should wait for, didn't follow the project so I am not up to date. Thank you for your time.

**Comment by Pololot64** [comment]
No problem :)

**Comment by Pololot64** [comment]
I'm sorry for the delay. The update should be approved by Microsoft around Monday. I am going to write a quick tutorial on how to change keyboard layouts soon too.
