### ISSUE TITLE
Error in .bashrc after instrumentation

### ISSUE THREAD

**Issue by memeplex** [Opticos/GWSL-Source#26]
GWSL has modified my .bashrc in a way that breaks it:

```
expr: syntax error: unexpected argument  '4'
sed: -e expression #1, char 1: unknown command: `,'
```

This is in a clean WSL2 Ubuntu 20.04 install.

**Comment by Pololot64** [comment]
This is a duplicate but that is ok. It wont do it any more after the coming update (1.3.7) but the breaking lines can easily be deleted.
