### ISSUE TITLE
Can't I install this on a different drive

### ISSUE THREAD

**Issue by alok-debnath** [Opticos/GWSL-Source#28]
Is it not possible to install this app on a different drive, Sorry I know that this is not an issue and should not be asked but I had doubts about it. When I first saw this app I thought that this app would allow me to to install a Linux Graphical Environment (GUI) seamlessly 😅

**Comment by Pololot64** [comment]
Unfortunately the way it is currently written makes it impossible to install on a separate drive. It could be changed but it would likely break lots of compatibility :(
