### ISSUE TITLE
Sharing clipboard problem

### ISSUE THREAD

**Issue by jvera701** [Opticos/GWSL-Source#31]
Hi,

Thanks for your work, this is a really cool project. I am currently using the GWSL version from github (1.3.7). When I use "test configuration" in the shortcut creator, I have no problem sharing clipboard between linux and windows. However, once I create the short cut with the "add to start menu" button and launch linux from there, clipboard sharing stops working. If it helps, I am using Windows 10 Home Insider Preview Build 21296. Thanks !

**Comment by Pololot64** [comment]
What is the current profile set in the GWSL systray right-click menu?

**Comment by jvera701** [comment]
I am not 100% sure what you are referring to, but in the right-click menu it says "shared clipboard ON"

**Comment by jvera701** [comment]
Ok, so I experimented a bit, and it seems to me that it works as expected when I create a clipboard when I use the "default" value for shared clipboard in the shortcut creator. However, it does NOT work when I create a clipboard with shared clipboard being enabled ...

**Comment by Pololot64** [comment]
Strange. I'll look into this.

**Comment by karasq** [comment]
I have same issue. When you "Test Configuration" in "Shortcut Creator" with "Shared Clipboard: Enable" then it works as expected. But after "Add to Start Menu"  when shortcut has --clip_enabled="Enabled" and you run program then clippboard is not working. Changing  argument in shortcut to --clip_enabled="Default" enable clipbaord sharing.

**Comment by Pololot64** [comment]
Fixed this issue in the code. It will be in GWSL 1.3.8! Sorry for the delay

**Comment by mi-hol** [comment]
Seems solved, hence should issue be closed to avoid confusions?
