### ISSUE TITLE
Dual screen apps opening in middle

### ISSUE THREAD

**Issue by SpontaneousDuck** [Opticos/GWSL-Source#32]
I have a two monitor setup on my computer. When a new linux app starts up that is not maximized, it will default to the exact center of the desktop instead of the center of the main monitor or one of the monitors. It is not really an issue since I can move the window after it opens but it would look a lot nicer if it did not perform like that. 

Amazing software otherwise! Everything else has worked without issue so far!

**Comment by Pololot64** [comment]
Unfortunately I can't think of any solution. By in the center you mean half on each display correct?

**Comment by SpontaneousDuck** [comment]
Yup! Like if you use an application with a splash screen, the splash will show up half on one screen and half on the other. I was not sure if the screen coordinates are calculated somewhere and combine the two screen currently in that calculation?

**Comment by Pololot64** [comment]
I think It probably is viewed as one screen. The problem is that usually apps themselves control where they go. Since there is no window manager in use with GWSL, I do not know how to control window position.

**Comment by SpontaneousDuck** [comment]
Ahhh, ok! It is not a huge issue so if there is no easy way to fix it then its not worth investigating. Thanks!
