### ISSUE TITLE
Root Password Saved as Plain Text in dashboard.log

### ISSUE THREAD

**Issue by davidshq** [Opticos/GWSL-Source#36]
Instances of plain text root password showing in dashboard.log:
21-02-10 09:49:21,482 - GWSL 1.3.7 - INFO - (run) WSL SHELL $ wsl.exe ~ -d Ubuntu . ~/.profile;nohup /bin/sh -c "echo "therootuserspassword" | sudo -H -S sudo /etc/init.d/dbus start &"

**Comment by Pololot64** [comment]
That is very true. I added the logging later so it makes sense. Thanks for bringing it up
