### ISSUE TITLE
Choosing a Dependency Management Solution

### ISSUE THREAD

**Issue by davidshq** [Opticos/GWSL-Source#37]
I'd like to contribute to the code. I noticed that there doesn't appear to be any dependency management setup at the moment. I'd be happy to do so but was wondering what dependency management solution you want to use:

- requirements.txt
- pyproject.toml (poetry)
- pipfile (pipenv)

The latter two have some significant advantages over requirements.txt option, but between pyproject and pipfile I have no preference.

**Comment by Pololot64** [comment]
I have slightly more experience with pipenv so pipfile is probably good. I have never done it before but contributions are great!
