### ISSUE TITLE
Issues Debugging Code Due to Calls to GWSL.exe

### ISSUE THREAD

**Issue by davidshq** [Opticos/GWSL-Source#40]
I can run GWSL for debugging purposes like so: `python main.py`

However, the tray menu doesn't work correctly for the dashboard, etc. as these menu items call GWSL. It is expecting to find GWSL at the root of the repo (and it isn't there).

I can run `python build.py` and build GWSL so that the files exist in the dist/GWSL folder but it looks like there are a lot of files in the distribution and I probably can't copy GWSL by itself into the root of my repo and would like to avoid cluttering the root of the repo with distribution files.

How are you handling this? I'm guessing I'm doing something simple wrong, but haven't figured it out yet!

**Comment by Pololot64** [comment]
I pretty much run main.py in the background in one python instance and the dashboard in whatever ide I am using. The dashboard will display an error but everything will still work enough for testing. You can also compile main by itself and run it where it is before running dashboard.py. They do not have to be run in the same directory.
