### ISSUE TITLE
Why do my windows close when my internet changes? WSL BUG

### ISSUE THREAD

**Issue by ByMartrixx** [Opticos/GWSL-Source#42]
If the internet connection is lost, the active windows on the x11 server will close, but the process will remain active.

**Steps to reproduce**
1. On any smartphone, turn on both mobile data and mobile hotspot
2. On the pc, connect to the hotspot network
3. Start any graphical app on GWSL
4. On the smartphone, turn off mobile data
5. The window with the graphical app will close
6. Use `ps` to check for running processes - the app process will still be active, but you won't be able to use it

**Comment by Pololot64** [comment]
This a common WSL issue unfortunately. I believe it is related to this https://github.com/microsoft/WSL/issues/4675
There are many more similar if not identical github issues relating to it. I cannot do anything about it.
