### ISSUE TITLE
Run with xlaunch created profile

### ISSUE THREAD

**Issue by sazconaitbit** [Opticos/GWSL-Source#46]
Hi, thanks for the awesome app!!

I have small issue to run qtCreator and make the launch apps works with OpenGL I need the Native opengl box of vcxsrv disabled I'm trying to get the same behavior with gwsl but not luck, any idea how can i get this?

Attached is the profile saved from xlaunch of vcxsrv 

```
<?xml version="1.0" encoding="UTF-8"?>
<XLaunch WindowMode="MultiWindow" ClientMode="NoClient" LocalClient="False" Display="-1" LocalProgram="xcalc" RemoteProgram="xterm" RemotePassword="" PrivateKey="" RemoteHost="" RemoteUser="" XDMCPHost="" XDMCPBroadcast="False" XDMCPIndirect="False" Clipboard="True" ClipboardPrimary="True" ExtraParams="" Wgl="False" DisableAC="True" XDMCPTerminate="False"/>
```

Update:

configuring GSWL vcxsrv flags i get this

`Error: couldn't get an RGB, Double-buffered visual
`
thanks!!

**Comment by Pololot64** [comment]
In GESL 1.3.7 (the latest), you can create xserver profiles which are similar. To add a profile, right-click the GWSL systray menu --> XServer Profiles --> Add a profile. Give it a name and then enter these flags. They are pretty much the same flags that xlaunch passes .  ```-nowgl -compositewm -multiwindow -clipboard -primary```

**Comment by sazconaitbit** [comment]
Thanks for your answer I try that but then when I try to run gui app I get this error:

`Error: couldn't get an RGB, Double-buffered visual`

**Comment by Pololot64** [comment]
Maybe try without -compositewm? Is the only thing that has changed since it worked GWSL?
