### ISSUE TITLE
No video when playing with ffplay, vlc, etc.

### ISSUE THREAD

**Issue by sergju** [Opticos/GWSL-Source#47]
No video when playing with ffplay, vlc, etc.

**Comment by Pololot64** [comment]
Is the window not showing up? Do other programs run? Is there a encoder error or anything? I do not have a problem so I need more info

**Comment by sergju** [comment]
Just black (or white) window. Sometimes on start I see some video glitches, but than nothing.
I've tried to play videos with other x server (X410) and all ok.

And I see next errors with ffplay
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

**Comment by Pololot64** [comment]
The two libgl errors are probably fine.. Does celluloid work?

**Comment by sergju** [comment]
Ok, but I don't see these errors with X410.
And yes, celluloid works.

**Comment by Pololot64** [comment]
Maybe try running the xserver with out using OpenGL on the windows side... It requires creating an xserver profile from the systray menu with these arguments: ```nowgl -compositewm -multiwindow -clipboard -primary```. Save the profile and switch to it

**Comment by sergju** [comment]
I created new profile, but crash happened with it.

**Comment by Pololot64** [comment]
Can you post your settings file (settings.json) here? Just make sure it does not have your IP in it. Also, can you post a screenshot of the crash?

**Comment by sergju** [comment]
Looks like you missed dash before nowgl and I just copied it. I added it and now have video.
Is it has a sense to add option -nowgl by default?

**Comment by Pololot64** [comment]
Oops! Sorry about that. I would add it by default but the problem is that different flags are needed in different cases. No matter what I change, there is always going to be an extra step needed for some. In this case the default is best to leave it as is. Now I can document this issue though so others know what to do :)
