### ISSUE TITLE
Alert always pop up

### ISSUE THREAD

**Issue by atardecer4** [Opticos/GWSL-Source#48]
**as the title, the Alert keep pop up after I click Yes, but look like it not affect using**

![image](https://user-images.githubusercontent.com/42576303/109266331-e203b300-7842-11eb-82ba-864ab43945bc.png)

**there is also no any log in the service.log**

![image](https://user-images.githubusercontent.com/42576303/109266761-6eae7100-7843-11eb-9733-24d82d27aeca.png)

**Comment by Pololot64** [comment]
I'll look into this. It may be due to the fact that your system localization and encoding is different than most. I think it might get fixed when I fix another issue so I'll get back to you on that.

**Comment by atardecer4** [comment]
noted, thank u
