### ISSUE TITLE
Resolution too low (Store version only)

### ISSUE THREAD

**Issue by brdhunga** [Opticos/GWSL-Source#5]
First of all, thanks for this awesome work. Secondly, the resolution seems too low. And this is after changing the LOW-DPI and HIGH-DPI options on the GWSL dashboard. 

Any guidance will be appreciated. Thanks !!

![image](https://user-images.githubusercontent.com/6069162/96372107-6b87d380-1133-11eb-98c0-03bf8fcc029a.png)

**Comment by Pololot64** [comment]
I am looking into this. I don't have an answer yet. Are you using the desktop or store GWSL?

**Comment by brdhunga** [comment]
Which one do you recommend between the desktop and store GWSL?

**Comment by Pololot64** [comment]
The Microsoft Store version is simpler to install and uninstall but it is easier to change the DPI options of the desktop version. I am releasing version 1.3.7 tomorrow and the desktop version will have a toggle to change scaling options

**Comment by Pololot64** [comment]
I am doing final testing and building as we speak

**Comment by brdhunga** [comment]
This is great. Once I try it, I can give feedback too. Thanks

**Comment by choldi** [comment]
I have 1.3.7 beta version, but I had the same problem,
I've set to HI-DPI and switch back to LOW-DPI worked for me.
You can check in .profile and .bashrc for GDK_SCALE and QT_SCALE_FACTOR and set to 1

GDK_SCALE=1
QT_SCALE_FACTOR=1

**Comment by Pololot64** [comment]
Sorry. I am still working on the manual for the full release so this is probably not obvious. Those settings only control the GTK and QT scaling. To use GTK scaling, you have to first tell Windows to stop scaling. I added a menu for this in the beta version. So it is a two step process. Right click the GWSL icon in the systray, hover over DPI Scaling Mode and click linux. Then click yes and the xserver will restart without extra WIndows scaling applied. Then GTK scaling will be in charge and will work properly.

![image](https://user-images.githubusercontent.com/31389383/103299569-76c46e80-49c2-11eb-9892-1465e87baf97.png)

**Comment by rommeswi** [comment]
Hi! Is there also a way to change the scaling on the store version?

**Comment by Pololot64** [comment]
Not yet. I am working on it. I found a way and have to implement it.

**Comment by LaravelFreelancerNL** [comment]
This workaround seems to solve the problem:
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
export GDK_SCALE=1

Source: https://github.com/microsoft/WSL/issues/5808

**Comment by Pololot64** [comment]
@LaravelFreelancerNL That is good but not actually related. The DPI is controlled both by Linux and windows. You use GDK_Scale to change it on the Linux side. This post is referring to the scaling performed on the Windows side.

**Comment by Pololot64** [comment]
Sorry for the delay. I implemented the changes and they will make their way into GWSL 1.3.8!
