### ISSUE TITLE
[Feature Request] Add option for run app in wayland mode

### ISSUE THREAD

**Issue by codehz** [Opticos/GWSL-Source#51]
Microsoft has released initial support for wayland in the latest preview version, it's time to add the option.
And the command line for launch app will looks like `C:\Windows\System32\wslg.exe ~ -d <Distro> gedit`

![image](https://user-images.githubusercontent.com/13158903/111885260-ab642700-8a01-11eb-9430-bc162b70a6b8.png)

(DPI Scaling is still an issue in the initial version)

**Comment by Pololot64** [comment]
I plan to do this in the future if Microsoft does not make GWSL completely obsolete. ATM I do not have the means to get the preview on a machine. What would the option look like for you do you think?

**Comment by codehz** [comment]
> What would the option look like for you do you think?

An switch button in application menu? Or set default mode and then right click menu to select alternative mode

At least for now X11 is better than wayland, because it won't be scaled like that screenshot...(also less bug like dialog shows behind main window, no IME support at all, and some graphics glitch

**Comment by Pololot64** [comment]
Sounds good. It is in my list. Maybe not for the next release but soon after if you want to test. I have not done much development lately because of business.

**Comment by SmartPolarBear** [comment]
Is this feature still available in the latest Insider Preview ? I tried and it yields no results.

**Comment by khuongduybui** [comment]
The feature is available to preview today in build 21364 (Dev channel insider)

**Comment by Pololot64** [comment]
Considering how it turned out I think GWSL will simply stay a separate option. The main differences will probably be speed, customizability with single window and fullscreen modes, better dpi (for now), and ssh gui options. Those are the pros of GWSL. Idk the benefits of builtin wayland yet other than removing one or two mouse clicks :D
