### ISSUE TITLE
[Feature request] Search bar in App List

### ISSUE THREAD

**Issue by atharos1** [Opticos/GWSL-Source#53]
Hi! I've been using GWSL to run graphical Linux apps alongside WSL2, and the experience has been great, so thank you for all this awesome work.

The one thing I would improve about the software, is adding a search bar to the App List, as that's something that I find myself missing each time I want to open a program. Other than that, great product as a whole.

Thank you!

**Comment by Pololot64** [comment]
Thanks for the feedback! There actually is a feature similar to this that already exists. If you type a letter while in the list, you can jump between names alphabetically. I was thinking of making it more obvious by adding a type-to-search label somewhere
