### ISSUE TITLE
GIMP crashing on startup

### ISSUE THREAD

**Issue by Agrover112** [Opticos/GWSL-Source#56]
I am unable to get GIMP running. It crashes on startup.
Are there any necessary details you would require from me?

**Comment by Pololot64** [comment]
GIMP tends to run bizarrely in WSL in my experience. One solution is to run vcxsrv in Fullscreen or single-window mode. The other is to just use the Windows version of GIMP

**Comment by Agrover112** [comment]
> GIMP tends to run bizarrely in WSL in my experience. One solution is to run vcxsrv in Fullscreen or single-window mode. The other is to just use the Windows version of GIMP

How should I do that?

**Comment by Pololot64** [comment]
Right click the gwsl systray icon --> XServer Profiles --> Single Window Mode. The windows version of gimp is here: https://www.gimp.org/downloads/

**Comment by Agrover112** [comment]
Thanks
