### ISSUE TITLE
Dashboard is not showing

### ISSUE THREAD

**Issue by justlunix** [Opticos/GWSL-Source#6]
I've tried both the Store and the Windows Traditional release, but the dashboard just does not show.
It doesn't matter whether I click the taskbar icon on the right or the open window.

![image](https://user-images.githubusercontent.com/66276367/96547266-17ecc580-12ac-11eb-806f-03a531d750cc.png)

Using Win 10 Pro

**Comment by Pololot64** [comment]
Could you post the logs? I think I know the reason but it would help to know the technical reasons. I think it is a theming related issue. Instructions to find logs: https://opticos.github.io/gwsl/tutorials/manual.html#finding-logs

**Comment by justlunix** [comment]
@Pololot64 Yea, seems to be something like that:

```2020-10-21 07:52:17,719 - __main__ - ERROR - Exception occurred
Traceback (most recent call last):
  File "manager.py", line 3200, in <module>
  File "manager.py", line 2867, in draw
ValueError: invalid color argument
```

This also spams the log quite a lot, making it reach 10gb for me already:
![image](https://user-images.githubusercontent.com/66276367/96678535-36b58f80-1372-11eb-9a4c-7c7d5027ef3d.png)

**Comment by Pololot64** [comment]
XD Yes. Luckily it is an extremely easy fix in the code. It will be fixed in the next release for sure ;)

**Comment by marvinhinz** [comment]
> XD Yes. Luckily it is an extremely easy fix in the code. It will be fixed in the next release for sure ;)

When is the next release expected? This tool seems great, cant wait to test it out :)

**Comment by Pololot64** [comment]
Probably not any time soon. I have no date because I am a student and it is a really busy time of year. I will do some work on a coming weekend. I am also doing this for free (And no donations so far) and school obviously gets priority. The current version works fine though and ou can get around this bug by changing the accent color.

**Comment by marvinhinz** [comment]
No problem, totally understandable! Ah sorry i didnt see the fix by using different accent color, ill try :)

**Comment by fsalinash** [comment]
Same happened for me. I know it's closed already but I'd like to post a solution for those who don't want to build from source:

- Right click on GWSL and select Configure GWSL
- Change "acrylic_enabled": true to false.
- Save changes.

That fixed it for me. Thanks for the great work, @Pololot64.

**Comment by Pololot64** [comment]
Just noting that it is not the same bug but @fsalinash's solution fixes the blank dashboard when you have HDR enabled. Thanks for posting it though. Also note that I do not recommend building from source. All the versions of 1.3.7 are in line with the current code now. And glad everything is working @fsalinash :)
