### ISSUE TITLE
[Bug/Enhancement] Some GUI programs require at least 1 file explorer to be installed

### ISSUE THREAD

**Issue by TheAlienDrew** [Opticos/GWSL-Source#62]
And most of the GUI programs will not install a file explorer by default.

Could there be a prompt, while installing GWSL, to automatically install one from a list of like maybe the top 5 file explorers?

**Comment by Pololot64** [comment]
This is a cool idea but normally I do not want GWSL to install any programs since it would make it more distro specific. Different distros have different package managers etc. A new webpage with some common file managers could be made though.

**Comment by TheAlienDrew** [comment]
True, but it wouldn't be too hard to figure out what package manager a distro has. (e.g. `command -v apt`)

**Comment by Pololot64** [comment]
That would make it easier. But I'd still rather not just to keep the system from getting more complicated. Sorry :(

**Comment by Pololot64** [comment]
(Keep it up with all the good ideas though) :)

**Comment by TheAlienDrew** [comment]
I mean I had another idea, but doubt it's possible... but maybe somehow integrate explorer.exe as the file manager for WSL? (WSL does support running Windows applications since the [Windows 10 Creator Update](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/)

**Comment by Pololot64** [comment]
Maybe not possible within GWSL but maybe a helper could be written that runs inside the distro. I will check it out

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by TheAlienDrew** [comment]
@Pololot64 for opening a directory from within any distro, just need to use explorer.exe "PATH HERE" (no need to convert to windows specific path).

This script looks like it will be handy in actually allowing file/folder selections for programs that need it: https://stackoverflow.com/questions/15885132/file-folder-chooser-dialog-from-a-windows-batch-script

**Comment by TheAlienDrew** [comment]
This could also be handy for different situations: https://ss64.com/nt/explorer.html

**Comment by Pololot64** [comment]
👍 Now we need a way to change the default file manager in linux. xdg-mime works in ubuntu and debian but not kali etc

**Comment by Pololot64** [comment]
Not sure what is called to open a file chooser in linux

**Comment by TheAlienDrew** [comment]
Yeah, though I was able to come up with this:

### windows-chooser-wrapper.sh
```sh
#!/bin/sh

# powershell script which will be ran in powershell via sh
ps1='Add-Type -AssemblyName System.Windows.Forms ; '
ps1="${ps1}$(echo '$f = new-object Windows.Forms.OpenFileDialog ; ')"
ps1="${ps1}$(echo '$f.InitialDirectory = pwd ; ')"
ps1="${ps1}$(echo '<# $f.Filter = "Text Files (*.txt)|*.txt|All Files (*.*)|*.*" ; #>')"
ps1="${ps1}$(echo '$f.ShowHelp = $true ; ')"
ps1="${ps1}$(echo '$f.Multiselect = $true ; ')"
ps1="${ps1}$(echo '[void]$f.ShowDialog() ; ')"
ps1="${ps1}$(echo 'if ($f.Multiselect) { $f.FileNames } else { $f.FileName }')"

# executes the powershell script above (filter temporarily turned off)
# 1. if path is a drive, it'll remove the colon (e.g. from "C:\...\..." to "C\...\...")
# 2. changes all back slashes to forward slashes (e.g. from "C\...\..." to "C/.../..." or from "\\wsl$\...\..." to "//wsl$/DISTRO_NAME/...")
# 3. changes the first character to lowercase; this only affects drive paths (e.g. from "C/.../..." to "c/.../...")
# 4. changes drive paths to corresponding path in wsl (e.g. from "c/.../..." to "/mnt/c/.../...")
# 5. changes windows path from wsl to actual wsl path (e.g. from "//wsl$/DISTRO_NAME/..." to "/...")
powershell.exe -c "$(echo "${ps1}" | sed 's/"/^"/g')" | sed '/^[A-Z]:\//s/://' | sed 's|\\|/|g' | awk '{ print tolower( substr( $0, 1, 1 ) ) substr( $0, 2 ); }' | sed '/^[a-z]\//s/^/\/mnt\//' | sed 's|^//wsl\$/[^/]*/|/|'
```

**Comment by Pololot64** [comment]
Apparenty applications also use dbus to spawn a chooser but wsl's big problem is already dbus XD

**Comment by TheAlienDrew** [comment]
Ah gotcha, I'm curious to know how the file chooser actually works, because if I know how, I can then change the script to match up as best as I can to a normal file chooser.

**Comment by TheAlienDrew** [comment]
> Linux's file chooser?

Yeah, I don't work a lot with system stuff to know how it passes 'file/folder' chooser information from application to linux to the file choosers, and then how it all get's passed back. Haven't taken any OS programming classes... xD

**Comment by Pololot64** [comment]
I'm not sure either
