### ISSUE TITLE
Initial Setup: Can't get GWSL to display any windows

### ISSUE THREAD

**Issue by DennisGaida** [Opticos/GWSL-Source#64]
Sorry for the generic error description, but I can't get GWSL to work (to display any window) even after running through the *Getting started* steps of the manual.

* I have installed GWSL from the Windows Store allowed all Firewall Access & have restarted the machine
* Running Windows 10 21H1 (v 19043.1032), WSL 2 & Debian distro
* I have enabled Auto-Export Display
* dashboard.log & service.log are 0 bytes

Checking my `.profile` file I can also see some GWSL entries, and checking env var `$ECHO` I see `172.19.112.1:0.0`.

I then tried installing **Microsoft Teams** and the app is also shown in the launcher in Linux Apps. Clicking on the app also launches the Teams instance, but I simply **don't see anything** (i.e. no window popping up). Clicking the teams app again (or starting `teams` from the shell launches new instances, but I simply don't see anything.

I'm sure I'm missing something I just don't know where to start and the manual isn't helping. Besides my problem I would love if we had some kind of "test app" that exists in pretty much all distros to see if GWSL is generally working (like Windows Notepad).

**Comment by Pololot64** [comment]
There is a test clock app built in that does not rely on any distro. Go to the Dashboard --> About --> XClock. Does it launch?

**Comment by DennisGaida** [comment]
Awesome! Didn't know about XClock (should be added to the manual to check that *Geting started* was succesful.

So maybe this is related to the app (Microsoft Teams) I'm trying to start, but I have no clue how to debug.

**Comment by Pololot64** [comment]
I will add that. What happens if you run an app like xterm in Linux? Does it work or give an error. Try running teams directly from bash too. Maybe it will give an error message there and shed more light on the problem

**Comment by DennisGaida** [comment]
Tried running directly from bash. Process starts - no window, no nothing. I know that it "should" work since there are tutorials out there just not for GWSL: https://developers.salestim.com/blog/install-microsoft-teams-linux-wsl-ubuntu/

Looking at the tutorial I see that I need DBUS, so I enabled that with GWSL, but that also wasn't enough. `xterm` works starting from bash as well as from GWSL. I'm assuming it is about the way Electron (Teams) works...

**Comment by DennisGaida** [comment]
Alright this is a specific Microsoft Teams issue and has nothing to do with GWSL. Sorry for wasting your time.

Additional test for "Getting started" could be to install the X11-Apps and run xcalc directly from bash - that also worked for me. X11-Apps are a bit smaller than xterm.

I checked the Teams log folder:  `~/.config/Microsoft/Microsoft Teams/logs` which showed a couple of errors such as libsecret not being installed (`sudo apt install libsecret-1-0`) and missing a hooks.js file... Teams starts now 👍

**Comment by Pololot64** [comment]
Cool 👍
