### ISSUE TITLE
[Bug] Multiple windows of the same application popup (6-7 windows I think)

### ISSUE THREAD

**Issue by TheAlienDrew** [Opticos/GWSL-Source#66]
GWSL is setup to auto start correctly.

I've noticed when trying to access GWSL after a shutdown/restart that it some times will bug out, opening multiple windows of an application. Most times, they were an app that I hadn't use at all recently.

First time it happened, it was with the application shortcut maker, and most recently, as of today, it was opening the WSL directory for my distro in Explorer.exe.

**Comment by Pololot64** [comment]
So the shortcut creator randomly opens? Or just random dashboard items? Are you possible scrolling when you mouse over them?

**Comment by TheAlienDrew** [comment]
> So the shortcut creator randomly opens? Or just random dashboard items? Are you possible scrolling when you mouse over them?

So far, the application is random, though I think you might be onto something with the scrolling. I do remember each time happening during the scrolling, but I didn't think it was related at all.

**Comment by TheAlienDrew** [comment]
But to note, what ever application it opens, it is is 6-7 windows of that same application.

**Comment by Pololot64** [comment]
It should not have to do with reboots... Unless I am crazy (which I am pretty sure I am not XD) it should be the scrolling. The graphics library I use detects scroll wheel movements as clicks and they happen rapid fire since it is a scrollwheel. GWSL closes automatically when it loses focus so the apps open too fast and GWSL does not lose focus fast enough to stop opening them

**Comment by TheAlienDrew** [comment]
Ah I see. I guess I just happen to open the menu after reboots lol. But yeah interesting that scrolling happens to do that.

**Comment by TheAlienDrew** [comment]
> It should not have to do with reboots... Unless I am crazy (which I am pretty sure I am not XD) it should be the scrolling. The graphics library I use detects scroll wheel movements as clicks and they happen rapid fire since it is a scrollwheel. GWSL closes automatically when it loses focus so the apps open too fast and GWSL does not lose focus fast enough to stop opening them

Ooooh, so scrolling outside the menu and then moving the mouse into the menu is likely what's causing it?

**Comment by TheAlienDrew** [comment]
Omg, yep, that's it. Scrolling outside the menu when open, and moving the cursor into the menu on any particular item in the menu is what causes the items to open rapidly.

**Comment by TheAlienDrew** [comment]
Sounds like it could be a very easy fix I assume?

**Comment by Pololot64** [comment]
Maybe. But updating GWSL is a hassle and I do not really plan on doing it any time soon. It was a ton of work to debug and write the last release

**Comment by TheAlienDrew** [comment]
Heh, I know what it's like. I've got a project of my own that I'm not looking forward to debugging and refactoring.
