### ISSUE TITLE
[Bug] Right-Click context menu hangs up application for a short while, and then shows menu options

### ISSUE THREAD

**Issue by TheAlienDrew** [Opticos/GWSL-Source#67]
Note: using short cut keys (Ctrl+P) does still work. Not sure why right-click isn't working though.

**Comment by TheAlienDrew** [comment]
Update: it seems to chug awhile before showing the right-click context menu. Maybe this is because I turned on indirect LibGL, but not sure.

**Comment by TheAlienDrew** [comment]
Nope, not because of indirect LibGL

**Comment by Pololot64** [comment]
Does it copy eventually? Things copy for me

**Comment by TheAlienDrew** [comment]
> Does it copy eventually? Things copy for me

Yes, eventually, and same for pasting. But it definitely likes to chug along slowly when it comes to showing the context menus

**Comment by TheAlienDrew** [comment]
Might just be Firefox, as that's the only application I've been using (for right-click context menus) at the moment, so that might be something to test.

**Comment by Pololot64** [comment]
👍
