### ISSUE TITLE
Launching tasklist through a cmd shell every few seconds is too slow

### ISSUE THREAD

**Issue by notsure2** [Opticos/GWSL-Source#68]
Hello,
Please switch to https://pypi.org/project/psutil/ for checking the process list as it calls directly into Win32 C API and bypasses the huge CPU spiking cost of launching cmd.exe (and any attached things like https://mridgers.github.io/clink/) and then the overhead of launching the second process tasklist.exe

Thank you.

**Comment by Pololot64** [comment]
I completely forgot to respond to this. I have implemented psutil and it will be out .. soon
