### ISSUE TITLE
Replace Icon with actual application icon

### ISSUE THREAD

**Issue by Scarwolf** [Opticos/GWSL-Source#69]
Instead of showing the GWSL Icon, wouldn't it be possible to replace the icon with the one from the actual opened application?
If you have run multiple programs, the current icon makes it hard to distinct at first glance.

**Comment by Pololot64** [comment]
That is determined by the application running. If the application supports it, it will use it's own icon, otherwise it will always fall back on the default gwsl. It would take alot to change it
