### ISSUE TITLE
No auth sock

### ISSUE THREAD

**Issue by kl3sk** [Opticos/GWSL-Source#70]
Hello,

Using VcXsrv before GWSL with Gitkrakn, I ran to this similar problem and solved it with [this solution](https://chuckdries.medium.com/installing-gitkraken-in-wsl-2-15bf6459f823#06f4) following [this thread](https://github.com/Microsoft/WSL/issues/3183#issuecomment-704693149) 

Everything worked, but when using GWSL this error came back.

![image](https://user-images.githubusercontent.com/2953145/121856259-98a57980-ccf4-11eb-9735-fb52742f6307.png)

And don't know/found how to solve it.

Thanks

**Comment by Pololot64** [comment]
I looked at the threads but do not completely understand what you mean. Which step exactly did you have to do before with vcxsrv?

**Comment by kl3sk** [comment]
Thanks for your answer 


I follow the step from the GitHub post. Copying it into my WSL (Debian) .bashrc


What informations do you need else ?

**Comment by Pololot64** [comment]
I don't see any reason why the bash code shouldn't work with GWSL... were you using any specific flags for vcxsrv?

**Comment by kl3sk** [comment]
I didn't set any flags, using the defaults.

**Comment by Pololot64** [comment]
What distro?

**Comment by kl3sk** [comment]
Disto. Debian 10

.profile is as default
.bashrc too (unless what we are talking about, and default "un"commented alias and colorization)

**Comment by Pololot64** [comment]
hmm

**Comment by kl3sk** [comment]
I am not currently on my computer. But tell me what you need and I'll give it to you as soon as I can.

**Comment by Pololot64** [comment]
👍 It is bizzare because GWSL is just vcxsrv, I need to think

**Comment by kl3sk** [comment]
Maybe because I use a private repo with ssh key auth?

**Comment by Pololot64** [comment]
Probably. But I don't see how the xserver affects that :-/

**Comment by kl3sk** [comment]
Hello,

I finally found a solution, I used to use SSH agent before GWSL (and worked perfectlly), but uncheck SSH agent and set the keys, it appears that GK allow me to push/pull correctlly now.

![image](https://user-images.githubusercontent.com/2953145/122017522-564a6e00-cdc2-11eb-9c8b-59829d4bddbd.png)

**Comment by kl3sk** [comment]
Hi, I reopen this issue, because I have to manage 2 different ssh keys, and the problem still remains.

**Comment by kl3sk** [comment]
I install keychain to manage ssh keys.

If it can help,
```bash
echo $SSH_AUTH_SOCK
```

return
```bash
/tmp/ssh-5b2plVYsijaV/agent.196
```

but gitkranken always says;
![image](https://user-images.githubusercontent.com/2953145/139944966-b1702f35-0ea9-4226-926b-c60b54437eae.png)

**Comment by kl3sk** [comment]
Update:

If I strat Gitkraken from the shell, the error fade away.

So it look like it is GWSL that do not read my `.bashrc`
