### ISSUE TITLE
No scrolling here??

### ISSUE THREAD

**Issue by latsa** [Opticos/GWSL-Source#72]
![2021-06-20_231114](https://user-images.githubusercontent.com/5510858/122687073-329d8280-d21d-11eb-92b1-0d157d7f223c.jpg)

**Comment by latsa** [comment]
When selecting Linux Apps from the menu, scrolling does not seem to work.

**Comment by Pololot64** [comment]
Are you trying to touch scroll? I only can support mouse-wheel scrolling

**Comment by latsa** [comment]
Mouse-wheel scrolling does not work. Mouse-wheel scrolling works otherwise. Mouse-click works. I'm on Windows 10 Home Build 19041.vb_release.191206-1406. GWSL Version 1.3.8.

**Comment by Pololot64** [comment]
Is there any error in the logs (go to dashboard/about and look at dashboard.log)

**Comment by latsa** [comment]
Both dashboard.log and service.log files are empty.

**Comment by mi-hol** [comment]
> Are you trying to touch scroll? I only can support mouse-wheel scrolling

I use GWSL on a laptop without mouse and native Windows apps can use touch scroll without issues/restrictions.
Could you please elaborate on the technical reason why this feature can't be supported?
Maybe someone has a solution.

BTW: GWSL is a great app, many thanks for making it available!

**Comment by Pololot64** [comment]
Glad you like it. The reason I cannot support touch scroll at the moment is because I wrote the GUI of GWSL from scratch without any gui toolkit libraries. There is nothing pre done. If I want to add touch scrolling or even a scrollbar I would have to write everything from scratch (eg. inertia, differentiating between mouse and finger etc). I did not focus on this before because most gui apps in linux don't support touch scrolling either.

**Comment by NotYetHAX** [comment]
i can't scroll too.

**Comment by NotYetHAX** [comment]
> i can't scroll too.

OH nvm i can scroll with A, S, D and F keys :D

**Comment by Pololot64** [comment]
I think you are simply jumping down the list to the letters you pressed... What mouse do you have for it to not work normally?

**Comment by NotYetHAX** [comment]
> I think you are simply jumping down the list to the letters you pressed... What mouse do you have for it to not work normally?

i resetted the gwsl settings then it worked! ( for me )

**Comment by Pololot64** [comment]
👍 Strange but I am glad it fixed it.

**Comment by mi-hol** [comment]
> scroll with A, S, D and F keys

well that is not really a solution meeting user expectations.
Laptop have touchpads and scrolling is one of their standard features

**Comment by mi-hol** [comment]
Would [this python code](https://python-forum.io/thread-31703.html) sample help?

**Comment by Pololot64** [comment]
Nope. It is unrelated.

**Comment by Pololot64** [comment]
> > scroll with A, S, D and F keys
> 
> well that is not really a solution meeting user expectations.
> Laptops have touchpads and scrolling via moving finger on right side is a standard feature users expect to work

It is an addition. Scrolling does work on most machines just saying :)

**Comment by Pololot64** [comment]
The best I could maybe do is a hidden button that scrolls down a couple icons at a time but I would rather not...

**Comment by Pololot64** [comment]
I implemented touch scrolling :D

**Comment by mi-hol** [comment]
Great news! Looking forward to the commit

**Comment by Pololot64** [comment]
I was finally able to release 1.3.9. Phew, now touch scrolling is enabled :D

**Comment by mi-hol** [comment]
Updates via Store require some time to tickle thru, could you please publish this version in github too?

**Comment by Pololot64** [comment]
Sure but not this weekend. I increased the store rollout percentage though so if you manually check it may come soon
