### ISSUE TITLE
Increase mouse cursor size

### ISSUE THREAD

**Issue by nistvan86** [Opticos/GWSL-Source#73]
I have a 4K display and I'm using my system with an increased Windows pointer size. However GWSL (vcxsrv?) uses the default X11 mouse pointer which is extremely small.
I presume the default multi window profile contains `-swcursor`, but creating a custom one without this doesn't seem to solve the issue.
Any idea how to deal with this?

**Comment by Pololot64** [comment]
There is no -swcursor in the default profile. Adding it may fix the problem.

**Comment by nistvan86** [comment]
Adding it makes no difference. And vcxsrv's help suggests that the presence of this switch should force the current behavior of not using Windows cursors.

		-swcursor
			Disable the usage of the Windows cursor and use the X11 software
			cursor instead.

That's why I thought it's enabled in the default profiles, but then it's not. So it's something else.

**Comment by Pololot64** [comment]
And GWSL is set to hidpi mode correct?

**Comment by nistvan86** [comment]
Assuming that the tray menu now allows me to change back to LOW-DPI, I guess so.
![image](https://user-images.githubusercontent.com/829428/122933435-f2e6b000-d36e-11eb-99f5-e4090fc8baa7.png)

**Comment by Pololot64** [comment]
That controls GTK and QT's hidpi. Try right clicking the GWSL systray menu and selecting Linux Scaling so that GTK scaling and QT scaling won't be overridden by Windows

**Comment by nistvan86** [comment]
Mouse cursor size is unaffected. Scaling did change, window contents became blurrier. (I prefer the Linux scaling)

**Comment by Pololot64** [comment]
Linux scaling is much nicer :) idk why the cursor is still small

**Comment by askingalot** [comment]
I realize this issue is closed, but I don't see a resolution to it. 

I'm having the same problem. I've tried both Windows and Linux scaling modes, but the mouse pointer remains tiny. Is there anything I can do?

**Comment by Pololot64** [comment]
Maybe try a new cursor "font"?
