### ISSUE TITLE
summarize solved issues as "Troubleshooting Guide" in wiki

### ISSUE THREAD

**Issue by mi-hol** [Opticos/GWSL-Source#75]
As you seem to like my proposal in [this post](https://github.com/Opticos/GWSL-Source/issues/30#issuecomment-871534712) generally, please be aware that I'd need your support to get some prerequisites met. 

Prerequisites I currently see are:

1. new labels need to be defined, intent documented & created to facilitate collaboration (creating a proposal as next task is to be created by me)
2. all issue currently used to keep troubleshooting knowhow need to be flagged by you
3. we need to agree on a procedure to review  proposed content and improving it, so it can be publish to wiki & issue be closed
4. most likely the work will happen in small chunks of 1-3 issues being WIP at a time

**Note**: some issues are very hard for me to summarize (i.e. Can't Open Apps from Linux Apps #59) 
Working out the exact details for troubleshooting of each case could be a lengthy process.
Therefore as a "quick start" I'd suggest to just reference the specific issue for this exercise instead of copying/writing a lot of text.

Does this make sense? 
Questions or comments?
Will it fit with your other work?

**Comment by mi-hol** [comment]
Here I found a good example for a "Troubleshooting Guide" related to X11 and WSL https://github.com/cascadium/wsl-windows-toolbar-launcher#troubleshooting

**Comment by mi-hol** [comment]
Proposal: new labels to facilitate collaboration on creating Troubleshooting Guide

Label | Intent
-- | --
Solution Here | flag issues with  knowhow for troubleshooting
WIP KnowledgeBase | work to convert into knowledge is in progress
Prio 1 KnowledgeBase | 	First priority for conversion to knowledge
Prio 2 KnowledgeBase | 	Second priority for conversion to knowledge

Process:

Sequence | Owner | Task
-- | -- | --
1 | Pololot64 | Review all open issues and either assign label „Solution Here“ or „Bug“ or close issue
2 | Pololot64 | for all issues with label „Solution Here“ assign priority via label „Prio 1 KnowledgeBase“ or „Prio 2 KnowledgeBase“
3 | Mi-hol | Select 1 to 3 issue(s) with label „Solution Here“ and assign „WIP KnowledgeBase“
4 | Mi-hol | Create PR with reference to issue
5 | Pololot64 | Review & merge PR

**Comment by Pololot64** [comment]
will do

**Comment by mi-hol** [comment]
> Will it fit with your other work?

based on recent comment, the answer seems a no

**Comment by Pololot64** [comment]
Cool. I will either be able to work on it tomorrow or the day after so that sounds good. (Also no pressure. I can write things myself as needed.) Again, thanks for your help :)

**Comment by Pololot64** [comment]
I made a new label Good for Reference

**Comment by Pololot64** [comment]
I did some cleanup. Linking would probably be fine for now. I can do a writeup for each later :)
