### ISSUE TITLE
Mouse hide not working

### ISSUE THREAD

**Issue by mobilegmYT** [Opticos/GWSL-Source#79]
Hello! I'm currently running Minecraft Pi Edition: Reborn. One issue I'm noticing is that the cursor is supposed to be hidden, which is what happens on normal Linux, but it doesn't hide when I play it with GWSL and WSL2. I'm wondering if this is a bug with the code, or just a thing that happens because of the way gwsl and xrcsrv windows interact? 

![image](https://user-images.githubusercontent.com/44128563/126677747-93dd7683-66a0-433e-b200-9c2216d03249.png)

**Comment by Pololot64** [comment]
I think it is inevitable. It could be happening anywhere down the line :(
