### ISSUE TITLE
[Question] Using GWSL with ZSH

### ISSUE THREAD

**Issue by Aaronzinhoo** [Opticos/GWSL-Source#8]
I have ZSH as my default shell and was wondering if I needed to add any extra lines to zshrc like for Fish? Thanks and really love the application!

**Comment by Aaronzinhoo** [comment]
Yea i was able to set the display but the shortcuts are not working sadly.

**Comment by Pololot64** [comment]
I will try to work on this eventually but I will have to do alot of learning. I might make it so that it is a plugin system or something. It will definitely be more modular. I can also give the code I have now and it can be ported

**Comment by Aaronzinhoo** [comment]
Yea a plug-in system would be great, then it could be easier to get other contributors working on this with you! Would love to help if this is the case (and time permits of course)

**Comment by Pololot64** [comment]
Help would be great! I have a few days coming up and I will really try to do a good amount of work on the project. There is sort of a feature freeze till I fix certain bugs but after that I will really look into fixing the specific part of code related to this. I am thinking about the various ways of implementing this. Then I will write a manual or something showing how to contribute. The readme is useless at this point.
