### ISSUE TITLE
Shortcut did not work.

### ISSUE THREAD

**Issue by Jason5Lee** [Opticos/GWSL-Source#84]
I try to create a shortcut. If I directly run that program in command line, it works fine. If I input the path in shortcut creator, and click "test configuration", it works fine. But when I run the created shortcut, it just has nothing pop up.

**Comment by Pololot64** [comment]
Is this the store version of GWSL? And is it version 1.3.9? If you are using the store version, what happens if you run gwsl.exe in cmd?

**Comment by Pololot64** [comment]
I can try to fix this before I leave for school in a week but I need more info

**Comment by Jason5Lee** [comment]
It turns out to be the problem of the program.

**Comment by Pololot64** [comment]
Phew :)
