### ISSUE TITLE
Option to not run GWSL_service

### ISSUE THREAD

**Issue by omar2205** [Opticos/GWSL-Source#86]
Is there a way to not launch gwsl service? it keeps spiking my CPU. 
Whenever I run something with GWSL, I usually kill it.

So maybe a run argument to not use it?

**Comment by Pololot64** [comment]
Are you on GWSL 1.3.8 or 1.3.9? 1.3.9 dramatically decreases cpu usage. I have not finished the rollout yet however so you may not have it yet.

**Comment by omar2205** [comment]
I'm running 1.3.9 (store)

**Comment by omar2205** [comment]
https://i.imgur.com/a2KYI5v.gifv

**Comment by Pololot64** [comment]
Strange. Did the performance improve or decrease since 1.3.8? Also, what are your specs. I can try to improve the performance but already there are not many heavy things running in the service...

**Comment by Pololot64** [comment]
I can do some optimizations. I'll see what I can do

**Comment by omar2205** [comment]
@Pololot64 did you push the update yet?

**Comment by Pololot64** [comment]
Not the one with the fixes. I am working on it still. I paused the rollout of 1.3.9 and 1.4 may come by Monday (I may have win32 builds available first)

**Comment by omar2205** [comment]
OK, have a nice weekend

**Comment by Pololot64** [comment]
Thanks. You too
