### ISSUE TITLE
Options appears in the right for RTL (RightToLeft) languages

### ISSUE THREAD

**Issue by MehdiChinoune** [Opticos/GWSL-Source#93]
I know for LTR languages options appears in the right near the taskbar icons, but for RTL languages it makes it appears near the start menu.
Please Fix this issue.

**Comment by Pololot64** [comment]
I need more information. What shows up on the wrong side? Maybe a screenshot?

**Comment by MehdiChinoune** [comment]
![Inkedgwsl_LI](https://user-images.githubusercontent.com/79349457/132098032-98e4263b-f251-4631-a228-a69ba01c548c.jpg)

**Comment by Pololot64** [comment]
You can fix this by: right-clicking the GWSL icon, configure GWSL, and changing ```"start_menu_mode": false``` to ```true```. Save the file and close it. GWSL will now open on the left side

**Comment by MehdiChinoune** [comment]
Thanks.

**Comment by Pololot64** [comment]
No problem :)
