### ISSUE TITLE
[Request] Shutdown WSL when on exit

### ISSUE THREAD

**Issue by Klbgr** [Opticos/GWSL-Source#94]
As WSL can use and hold a lot of RAM, i always shut it down when i don't need it anymore with this command : `wsl --shutdown`.
So i'm asking you if you could add an option to shutdown WSL when exiting GWSL.
Thanks in advance.

**Comment by Pololot64** [comment]
It is technically possible but is a bad idea for widespread use. Many people might keep working using the terminal after exiting GWSL. If GWSL forced a WSL shutdown it would cause any background activity to crash. This could cause data loss and more would regard it as a bug.

**Comment by Klbgr** [comment]
Ok nevermind then. I did it by myself here : https://github.com/Klbgr/GWSL-Source/commit/4df57d8353999e5f5dbbdebaf94b24007d699466
Thanks anyway for replying.

**Comment by Pololot64** [comment]
:)
