### ISSUE TITLE
Funny wsl distros ?

### ISSUE THREAD

**Issue by neradp** [Opticos/GWSL-Source#95]
Why i have non existent wsl distros in GWSL Distro list ?

**Comment by Pololot64** [comment]
Please post a screenshot or list.

**Comment by neradp** [comment]
![2021-09-10_5-32-34](https://user-images.githubusercontent.com/7801598/132796185-cee78fea-d296-4fd5-af8e-44fce223a67c.png)
![2021-09-10_5-39-35](https://user-images.githubusercontent.com/7801598/132796189-933bcd12-6c75-41f8-b360-aa749cc5e5e7.png)
![2021-09-10_5-40-23](https://user-images.githubusercontent.com/7801598/132796193-4214c20c-83d5-4bb5-9e7f-eec0d847e2a2.png)
![2021-09-10_5-41-11](https://user-images.githubusercontent.com/7801598/132796201-47ac9229-9e4a-4030-a892-35af1dd2243e.png)

**Comment by neradp** [comment]
It is a random on every run. I have only Ubuntu and Docker.
![2021-09-10_5-44-35](https://user-images.githubusercontent.com/7801598/132796388-fe5d6221-8083-4dcc-bd42-011d4601ca6b.png)

**Comment by Pololot64** [comment]
Ah yes.. well GWSL is literally running what you ran and parsing the lines as distros... I assume you have replaced cmd with powershell and added the random string magic to your profile? I cannot really fix this as it is not a bug strictly speaking but as long as you don't click them I guess everything should still work.

**Comment by neradp** [comment]
It could parse just wsl -l output.. Lines after: Windows Subsystem for Linux Distributions:

**Comment by Pololot64** [comment]
The problem is that this string changes with different locales, encoding, etc. It is not a top priority as it is extremely rare and I do not have time to fix it. A fix would likely have unintended consequences.
