### ISSUE TITLE
how to change font from gwsl dashboard

### ISSUE THREAD

**Issue by nanagami1369** [Opticos/GWSL-Source#96]
The dashboard fonts don't support my country's language and can't be read. 
How do I change the dashboard font?

![image](https://user-images.githubusercontent.com/38910015/132930717-197d660f-6efe-4fe6-bf49-685fc877c6d5.png)

**Comment by Pololot64** [comment]
The font cannot be changed. Sorry :( I tried to implement this earlier but the libraries I used made it extremely difficult. You could maybe install the github version and replace fonts but I cannot say what would happen.

**Comment by nanagami1369** [comment]
Alright! thank you for teaching me.
