### ISSUE TITLE
Config to turn off autocopy on text hightlighting.

### ISSUE THREAD

**Issue by VovkGeorgy** [Opticos/GWSL-Source#99]
Regular things:
I coppy some text from windows (base system) and then want to past this text in Webstorm which is opeden in Ubuntu wsl.
If i will hightlight some text in this wsl window it will replace my text in clipboard.

This outo-copy on hightlight is really annoing. It would be good to have a config for that.

**Comment by Pololot64** [comment]
From the discord server: create a new xserver config (GWSL right click menu --> xserver profiles --> create new profile) and use the arguments ```-wgl -compositewm -multiwindow -clipboard -noprimary```. Then switch to this profile.

Hope that helps :)

**Comment by VovkGeorgy** [comment]
@Pololot64 Thank you! This realy helped!

**Comment by cardin** [comment]
I feel like this should be mentioned in an Config FAQ or be a toggleable config in the dashboard

**Comment by Pololot64** [comment]
> I feel like this should be mentioned in an Config FAQ or be a toggleable config in the dashboard

I can possibly copy some of the xserver profiles from the discord into the manual. However, they are really machine specific oftentimes so I am not planning on adding more buttons.
